// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

using NUnit.Framework;
using BloodBankManagementSystem.UI.Test; //TODO: Change with accurate namespace
using System.IO;
using System.Windows.Forms;
using System.Drawing;


// Test Class
public class frmDonors_Clear_15d01529c9
{
    private frmDonors _frmDonors;
    private string _applicationPath;
    
    [SetUp]
    public void Setup()
    {
        _frmDonors = new frmDonors();
        _applicationPath = Application.StartupPath.Substring(0, (Application.StartupPath.Length) - 10);
    }

    [Test]
    public void ClearTextBoxes_AssertTextBoxesAreEmpty()
    {
        _frmDonors.Clear();

        Assert.IsEmpty(_frmDonors.txtFirstName.Text);
        Assert.IsEmpty(_frmDonors.txtLastName.Text);
        Assert.IsEmpty(_frmDonors.txtEmail.Text);
        Assert.IsEmpty(_frmDonors.txtDonorID.Text);
        Assert.IsEmpty(_frmDonors.cmbGender.Text);
        Assert.IsEmpty(_frmDonors.cmbBloodGroup.Text);
        Assert.IsEmpty(_frmDonors.txtContact.Text);
        Assert.IsEmpty(_frmDonors.txtAddress.Text);
    }

    [Test]
    public void ClearImage_AssertTheImageIsNoImage()
    {
        _frmDonors.Clear();

        string noImagePath = _applicationPath + "\\images\\no-image.jpg";
        using (var noImageBitmap = new Bitmap(noImagePath))
        {
            Assert.AreEqual(noImageBitmap, _frmDonors.pictureBoxProfilePicture.Image);
        }
    }

    [TearDown]
    public void TearDown()
    {
        _frmDonors.Dispose();
    }
}
